// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVOpo3temQ4DpOn5Fvlqt63ow4AUBB5ac',
    appId: '1:361952428559:web:e5b8e7bbbf6d69c6dc997a',
    messagingSenderId: '361952428559',
    projectId: 'trouvemoi-ad8fd',
    authDomain: 'trouvemoi-ad8fd.firebaseapp.com',
    storageBucket: 'trouvemoi-ad8fd.firebasestorage.app',
    measurementId: 'G-710Q9PSHJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4mAy3uhyg4BF5pDnSS0CWmedeWnbV6j0',
    appId: '1:361952428559:android:dbe9a79e72f8cddadc997a',
    messagingSenderId: '361952428559',
    projectId: 'trouvemoi-ad8fd',
    storageBucket: 'trouvemoi-ad8fd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9a0_27c6xfxGP6j4OPOWKb7Mxvh95gfs',
    appId: '1:361952428559:ios:9edbeb1079eb4f51dc997a',
    messagingSenderId: '361952428559',
    projectId: 'trouvemoi-ad8fd',
    storageBucket: 'trouvemoi-ad8fd.firebasestorage.app',
    iosClientId: '361952428559-cba6ju1a93f9e0tnv4mnmhol7lvfrlai.apps.googleusercontent.com',
    iosBundleId: 'com.leloeduk.trouvemoi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9a0_27c6xfxGP6j4OPOWKb7Mxvh95gfs',
    appId: '1:361952428559:ios:9edbeb1079eb4f51dc997a',
    messagingSenderId: '361952428559',
    projectId: 'trouvemoi-ad8fd',
    storageBucket: 'trouvemoi-ad8fd.firebasestorage.app',
    iosClientId: '361952428559-cba6ju1a93f9e0tnv4mnmhol7lvfrlai.apps.googleusercontent.com',
    iosBundleId: 'com.leloeduk.trouvemoi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVOpo3temQ4DpOn5Fvlqt63ow4AUBB5ac',
    appId: '1:361952428559:web:55137a689f900193dc997a',
    messagingSenderId: '361952428559',
    projectId: 'trouvemoi-ad8fd',
    authDomain: 'trouvemoi-ad8fd.firebaseapp.com',
    storageBucket: 'trouvemoi-ad8fd.firebasestorage.app',
    measurementId: 'G-0VHW2J8JGQ',
  );
}
